"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.metadata = void 0;
exports.default = RootLayout;
const google_1 = require("next/font/google");
const ui_components_1 = require("@bridgewise/ui-components");
require("./globals.css");
const geistSans = (0, google_1.Geist)({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});
const geistMono = (0, google_1.Geist_Mono)({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});
exports.metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
function RootLayout({ children, }) {
    return (<html lang="en" suppressHydrationWarning>
      <head>
        <ui_components_1.ThemeScript />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ui_components_1.ThemeProvider defaultMode="system">
          <ui_components_1.TransactionProvider>
            {children}
          </ui_components_1.TransactionProvider>
        </ui_components_1.ThemeProvider>
      </body>
    </html>);
}
//# sourceMappingURL=layout.js.map